# Generated by Django 5.2.3 on 2025-06-23 13:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_files/')),
                ('original_name', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_download', models.DateTimeField(blank=True, null=True)),
                ('special_link', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
